2020-05-09 18:34:17,575 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:67]
2020-05-09 18:34:17,586 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
2020-05-09 18:34:17,586 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
2020-05-09 18:40:29,864 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:67]
2020-05-09 18:40:29,872 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
2020-05-09 18:40:29,872 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
2020-05-09 18:40:49,679 ERROR: Exception on /auth/reset_password_request [POST] [in c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\misc\CS\Projects\microblog\app\auth\routes.py", line 54, in reset_password_request
    send_password_reset_email(user)
  File "C:\misc\CS\Projects\microblog\app\auth\email.py", line 15, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-05-09 18:40:49,679 ERROR: Exception on /auth/reset_password_request [POST] [in c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\misc\cs\projects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\misc\CS\Projects\microblog\app\auth\routes.py", line 54, in reset_password_request
    send_password_reset_email(user)
  File "C:\misc\CS\Projects\microblog\app\auth\email.py", line 15, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-05-09 18:43:18,733 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:67]
2020-05-09 18:43:18,734 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
2020-05-09 18:43:18,734 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
2020-05-09 22:34:39,076 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:67]
2020-05-09 22:34:39,084 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
2020-05-09 22:34:39,084 INFO: Microblog startup [in C:\misc\CS\Projects\microblog\app\__init__.py:85]
